layout_spectrum: 0.1163843
name: Radioactive man
typography_spectrum: 0.5100338
color:
  brandStrength: 0.8787234
  saturation: 0.5557069
  brandColors:
    - '#E3F0F3'
    - '#88888F'
    - '#573931'
    - '#DFB967'
    - '#B31945'
  lightness: 0.1729274
  rhythmicContrast: 0.5566552
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
